### ISSUE TITLE
MVPリリースの提出

### ISSUE THREAD

**Issue by norikawasonoka** [norikawasonoka/ruby#4]
## 各種情報
サービス名　お箏診断（仮）
サービスURL　https://glacial-wave-57337-b56375cc3d69.herokuapp.com/
等を記載してください

## READMEレビュー時にMVPリリース時点で実装予定だった機能
-[ ] ユーザー登録機能→面談でMVPリリース時にはいらないと判断したため→本リリースでLINEログイン機能つける予定
[ ] ログイン機能→面談でMVPリリース時にはいらないと判断したため→本リリースでLINEログイン機能つける予定
[ ] パスワード変更機能→本リリースでLINEログイン機能つける予定のためいらないと判断
[ ] 診断機能→diagnosisファイルにあり
[ ] お気に入り機能登録→youtubeの音楽を埋め込みユーザーのyoutubeでお気に入り登録できるため不要と判断
[ ] お気に入り機能→youtubeの音楽を埋め込みユーザーのyoutubeでお気に入り登録できるため不要と判断
[ ] お気に入り削除→youtubeの音楽を埋め込みユーザーのyoutubeでお気に入り登録できるため不要と判断
[ ] 診断機能結果→resultファイルにあり
[ ] お箏の道具→okotosファイルにあり
[ ] お箏の演奏技術→okotosファイルにあり
[ ] お問い合わせフォーム→面談でMVPリリース時にはいらないと判断したため→本リリースでつける予定

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
なければこの項目は省略してください
作らなくなった機能
[ ] お気に入り機能登録
[ ] お気に入り機能
[ ] お気に入り削除
本リリースに変更
[ ] ユーザー登録機能
[ ] お問い合わせフォーム
[ ] プライバシーポリシー、利用機能
機能追加（本リリースで追加）
・LINEのログイン機能
・LINEで新曲追加が通知が行くようにする機能
・xで曲の共有機能→ログインしなくても共有できる設定の予定
・診断機能もログインしなくてもできる予定

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします
ユーザーが触れない機能MVPリリース時点でないです

**Comment by norikawasonoka** [comment]
![スクリーンショット 2024-08-29 104043](https://github.com/user-attachments/assets/615164c9-b0dc-4a95-87a4-b4c966c8eb1b)
![スクリーンショット 2024-08-29 110455](https://github.com/user-attachments/assets/228a51ee-35a6-41f2-89e1-efc01d7849a4)

サービスイメージがわかるようなスクリーンショットです。

よろしくお願いします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
